{{-  if and .Values.pvc .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default .Release.Name }}-pvc
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: {{ .Values.pvc.storageClassName }}
{{- end }}